[
    {
       "name":"程序猿数学基础",
       "url":"https://alili.tech/tags/%E6%95%B0%E5%AD%A6/",
       "desc":"程序员的数学基础课学习笔记"
    },
    {
        "name":"微前端系列文章",
        "url":"https://alili.tech/tags/microfrontend/",
        "desc":"讲述我的微前端的落地历程"
     },
    {
       "name":"跨端开发系列文章",
       "url":"https://alili.tech/tags/%E8%B7%A8%E7%AB%AF%E5%BC%80%E5%8F%91/",
       "desc":"我们是如何一套代码跑8个端的实践心得"
    },
    {
        "name":"AliToSign",
        "url":"https://github.com/Num142857/AliToSign",
        "desc":"基于nodejs的阿里云API签名生成工具"
     },
    {
       "name":"StillFantasy",
       "url":"https://github.com/Num142857/StillFantasy/",
       "desc":"歌词自动下载工具"
    }
]