# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Hexo Blog

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        
    - name: Install dependencies and build
      env: 
        DEPLOY_BLOG: ${{secrets.DEPLOY_BLOG}}
      run: |
        git config --global user.name "codcer"
        git config --global user.email "codcer@gmail.com"
        rm -rf public
        npm install
        npm run build
        echo 'Build done

